### ISSUE TITLE
Multi-coil NUFFT interface

### ISSUE THREAD

**Issue by jyhmiinlin** [CEA-COSMIC/pysap#74]
Hello,

I am the author of PyNUFFT. I have almost finished your suggested ideas which are very helpful. Actually, the improved version is beyond my original expectation, which I would acknowledge your contribution to the PyNUFFT repository. 

Now I am facing a choice about the multi-coil version, which can be the following two different choices (I have both transforms):

**1.** Multiple-images to multiple data, and multiple data to multiple images. For example, (256,256, Nc) image -> (65536, Nc) data, or (65536, Nc) data -> (256,256, Nc) image.

**2.** Single-image to multiple data, multiple data to single-image. For example, (256,256) image -> (65536, Nc) data, or (65536, Nc) data -> (256,256) image. However, this involves sensitivities and a final combination is a must. 

My personal preference is 1 because it is a simple transformation without coil sensitivities. However, 2 is more common in MRI community but it introduces the extra complexity. 

Just want to listen to your opinion so I would formulate the code as the most natural way. 

Regars, 

Jyh-Miin

**Comment by LElgueddari** [comment]
Hey, 

Thank you for the update,
I will go probably for the first version that you propose, because of two advantages:
- You can go from choice 1 to 2 with low cost computation (product, sum, conjugate), which doesn't require GPU acceleration 
- The 2. is more general than the 1. because it allows you to do "classic MR reconstruction" (i.e. with coil sensitivity) but also calibration-less reconstruction.

Regards,

**Comment by jyhmiinlin** [comment]
OK!
